name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        BUILD_TYPE: ["Debug", "Release"]
        os: [ windows-latest ]
    steps:
    - uses: actions/checkout@v2

    - name: Get MSVC
      uses: ilammy/msvc-dev-cmd@v1
      if: ${{ matrix.os == 'windows-latest' }}

    - name: Get specific version CMake, v3.21.2
      uses: lukka/get-cmake@v3.21.2

    - name: run cmake
      run: > 
        cmake . -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} -B build

    - name: run build
      run: cmake --build build --config ${{ matrix.BUILD_TYPE }}
    
    # - name: run test
    #   run: ctest -C ${{ matrix.BUILD_TYPE }} --test-dir build